### ISSUE TITLE
安装后无法import插件

### ISSUE THREAD

**Issue by forchannot** [nicklly/nonebot2_covid_plugin#1]
nonebot beta2，通过nb命令安装后无法import，如图所示，请问怎么解决
![image](https://user-images.githubusercontent.com/100580891/169863875-4a2ad731-90d8-430e-abc7-807953c6d923.png)

**Comment by unights** [comment]
nonebot2_plugin_covid 而不是
nonebot_plugin_covid

**Comment by forchannot** [comment]
> nonebot2_plugin_covid 而不是 nonebot_plugin_covid

readme文档给的命令安装就是这个啊

**Comment by unights** [comment]
> > nonebot2_plugin_covid 而不是 nonebot_plugin_covid
> 
> readme文档给的命令安装就是这个啊

安装是 `pip install nonebot_plugin_covid`，但是模块名是 `nonebot2_plugin_covid`，导入应使用 `import nonebot2_plugin_covid`。

当然，这可能是一个发布时产生的问题。

**Comment by nicklly** [comment]
不需要import 使用nb或者pip安装之后 配置相关api的密钥就能用了

**Comment by nicklly** [comment]
> 

仓库名是仓库名 只要商店的命令没错就行 （确信

**Comment by nicklly** [comment]
已修复 没把所有东西都打包进去。。。
