### ISSUE TITLE
插件加载都没问题，但是在收到命令后报错

### ISSUE THREAD

**Issue by Nana7mij** [nicklly/nonebot2_covid_plugin#2]
![图片](https://user-images.githubusercontent.com/91075288/170418970-b278e20b-9c64-4c5a-9d80-6a50915ca355.png)

**Comment by nicklly** [comment]
> ![图片](https://user-images.githubusercontent.com/91075288/170418970-b278e20b-9c64-4c5a-9d80-6a50915ca355.png)

nb2 b3的bug 请回退b2
